//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryPizzaExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_InventoryItemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_InventoryItemMaster()
        {
            this.I_RecipeDetails = new HashSet<I_RecipeDetails>();
        }
    
        public int Id { get; set; }
        public int ItemCode { get; set; }
        public string ItemName { get; set; }
        public int MajorItemId { get; set; }
        public Nullable<int> MinorItemId { get; set; }
        public Nullable<int> PrimaryUnit { get; set; }
        public Nullable<decimal> PrimaryUnitConv { get; set; }
        public Nullable<int> ReportingUnit { get; set; }
        public Nullable<decimal> ReportingUnitConv { get; set; }
        public Nullable<int> StoreUnit { get; set; }
        public Nullable<decimal> StoreUnitConv { get; set; }
        public Nullable<decimal> LossPercentage { get; set; }
        public Nullable<decimal> GainPercentage { get; set; }
        public Nullable<decimal> ThersoldRecieving { get; set; }
        public Nullable<int> FixedorVariable { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual I_ItemMater I_ItemMater { get; set; }
        public virtual I_ItemMater I_ItemMater1 { get; set; }
        public virtual I_UnitMaster I_UnitMaster { get; set; }
        public virtual I_UnitMaster I_UnitMaster1 { get; set; }
        public virtual I_UnitMaster I_UnitMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RecipeDetails> I_RecipeDetails { get; set; }
    }
}
