//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryPizzaExpress
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryModuleEntities : DbContext
    {
        public InventoryModuleEntities()
            : base("name=InventoryModuleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<I_ItemMater> I_ItemMater { get; set; }
        public virtual DbSet<I_UnitMaster> I_UnitMaster { get; set; }
        public virtual DbSet<I_InventoryItemMaster> I_InventoryItemMaster { get; set; }
        public virtual DbSet<I_MenuItems> I_MenuItems { get; set; }
        public virtual DbSet<I_Recipe> I_Recipe { get; set; }
        public virtual DbSet<I_RecipeDetails> I_RecipeDetails { get; set; }
    }
}
