
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventoryPizzaExpress
{

using System;
    using System.Collections.Generic;
    
public partial class I_MenuItems
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public I_MenuItems()
    {

        this.I_RecipeDetails = new HashSet<I_RecipeDetails>();

    }


    public int Id { get; set; }

    public Nullable<int> ItemCode { get; set; }

    public string Name { get; set; }

    public Nullable<decimal> Price { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<I_RecipeDetails> I_RecipeDetails { get; set; }

}

}
