
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventoryPizzaExpress
{

using System;
    using System.Collections.Generic;
    
public partial class I_OrderDetails
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public I_OrderDetails()
    {

        this.I_OrderItemCatalog = new HashSet<I_OrderItemCatalog>();

    }


    public int Id { get; set; }

    public int StoreId { get; set; }

    public System.DateTime DeliveryDate { get; set; }

    public string Reference { get; set; }

    public string OrderNo { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<int> UerId { get; set; }

    public string Reason { get; set; }

    public Nullable<int> VendorId { get; set; }

    public string TranferNo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<I_OrderItemCatalog> I_OrderItemCatalog { get; set; }

    public virtual Store_Details Store_Details { get; set; }

}

}
