
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventoryPizzaExpress
{

using System;
    using System.Collections.Generic;
    
public partial class I_OrderItemCatalog
{

    public int Id { get; set; }

    public int OrderId { get; set; }

    public int ItemsId { get; set; }

    public string ItemName { get; set; }

    public Nullable<int> Unit { get; set; }

    public Nullable<decimal> Qty { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<decimal> onHand { get; set; }

    public Nullable<decimal> onOrder { get; set; }

    public Nullable<int> Vendor { get; set; }

    public Nullable<int> FixedorVariable { get; set; }

    public Nullable<decimal> TotalSum { get; set; }

    public Nullable<int> Status { get; set; }

    public string Createdby { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }



    public virtual I_OrderDetails I_OrderDetails { get; set; }

    public virtual I_UnitMaster I_UnitMaster { get; set; }

}

}
