
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventoryPizzaExpress
{

using System;
    using System.Collections.Generic;
    
public partial class I_RecievingItemCatalog
{

    public int Id { get; set; }

    public string OrderIds { get; set; }

    public string ReceiptNo { get; set; }

    public string Ref { get; set; }

    public Nullable<System.DateTime> DelieveryDate { get; set; }

    public Nullable<int> Status { get; set; }

}

}
