
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventoryPizzaExpress
{

using System;
    using System.Collections.Generic;
    
public partial class I_StockTakingItemCatalog
{

    public int Id { get; set; }

    public Nullable<int> StockTakingId { get; set; }

    public Nullable<int> ItemGroupId { get; set; }



    public virtual I_StockTaking I_StockTaking { get; set; }

}

}
