
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventoryPizzaExpress
{

using System;
    using System.Collections.Generic;
    
public partial class I_StockTaking
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public I_StockTaking()
    {

        this.I_StockTakingItemCatalog = new HashSet<I_StockTakingItemCatalog>();

    }


    public int Id { get; set; }

    public int StoreId { get; set; }

    public System.DateTime Date { get; set; }

    public int InventoryTime { get; set; }

    public Nullable<System.TimeSpan> InventoryTimeValue { get; set; }

    public int ClosingMethod { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<I_StockTakingItemCatalog> I_StockTakingItemCatalog { get; set; }

    public virtual Store_Details Store_Details { get; set; }

}

}
