
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventoryPizzaExpress
{

using System;
    using System.Collections.Generic;
    
public partial class I_VendorItemCatalog
{

    public int Id { get; set; }

    public int ItemId { get; set; }

    public string ItemName { get; set; }

    public string ItemCode { get; set; }

    public decimal Price { get; set; }

    public int VendorId { get; set; }

    public int Unit { get; set; }

    public int FixedorVariable { get; set; }

    public System.DateTime DateEffectiveFrom { get; set; }

    public System.DateTime DateEffectiveTo { get; set; }

    public int Status { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

}

}
