
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventoryPizzaExpress
{

using System;
    using System.Collections.Generic;
    
public partial class I_VenderMaster
{

    public int Id { get; set; }

    public string VenderName { get; set; }

    public string AddressLine { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Country { get; set; }

    public decimal Phone { get; set; }

    public string Email { get; set; }

    public string GSTIN { get; set; }

    public string CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public Nullable<System.DateTime> ModifiedOn { get; set; }

}

}
