
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventoryPizzaExpress
{

using System;
    using System.Collections.Generic;
    
public partial class mi_def
{

    public int mi_def_Id { get; set; }

    public int storeid { get; set; }

    public int mi_seq { get; set; }

    public Nullable<int> obj_num { get; set; }

    public string name_1 { get; set; }

    public string name_2 { get; set; }

    public Nullable<int> maj_grp_seq { get; set; }

    public Nullable<int> fam_grp_seq { get; set; }

    public Nullable<int> mi_grp_seq { get; set; }

    public Nullable<int> mi_slu_seq { get; set; }

    public Nullable<int> price_grp_seq { get; set; }

    public Nullable<int> slu_priority { get; set; }

    public Nullable<int> nlu_grp { get; set; }

    public Nullable<decimal> nlu_num { get; set; }

    public Nullable<int> key_num { get; set; }

    public Nullable<int> icon_id { get; set; }

    public string ob_mi31_chk_mi_avail { get; set; }

    public string ob_mi44_no_edit_in_mgr_proc { get; set; }

    public string ob_item_is_the_no_modifier { get; set; }

    public string ob_lite_mi_dirty { get; set; }

    public string ob_rsvd01 { get; set; }

    public string ob_rsvd02 { get; set; }

    public string ob_rsvd03 { get; set; }

    public string ob_rsvd04 { get; set; }

    public Nullable<int> mi_type_seq { get; set; }

    public Nullable<int> cond_grp_mem_seq { get; set; }

    public Nullable<int> cond_req { get; set; }

    public Nullable<int> cond_allowed { get; set; }

    public Nullable<int> crs_mem_seq { get; set; }

    public Nullable<int> crs_sel_seq { get; set; }

    public Nullable<int> mlvl_class_seq { get; set; }

    public Nullable<int> prn_def_class_seq { get; set; }

    public Nullable<int> product_seq_1 { get; set; }

    public Nullable<int> product_seq_2 { get; set; }

    public Nullable<int> product_seq_3 { get; set; }

    public Nullable<int> product_seq_4 { get; set; }

    public Nullable<decimal> comm_amt { get; set; }

    public Nullable<decimal> comm_pcnt { get; set; }

    public string cross_ref1 { get; set; }

    public string cross_ref2 { get; set; }

    public Nullable<int> ob_flags { get; set; }

    public string ob_workstation_only { get; set; }

    public Nullable<int> mi_slu2_seq { get; set; }

    public Nullable<int> prep_time { get; set; }

    public Nullable<int> external_type { get; set; }

    public Nullable<int> topping_type_seq { get; set; }

    public Nullable<int> topping_modifier_seq { get; set; }

    public Nullable<int> last_updated_by { get; set; }

    public string last_updated_date { get; set; }

    public Nullable<int> multi_user_access_seq { get; set; }

    public Nullable<int> build_screen_style_seq { get; set; }

    public Nullable<int> hht_build_screen_style_seq { get; set; }

    public Nullable<int> prefix_override_count { get; set; }

    public Nullable<int> prefix_override_level { get; set; }

    public Nullable<int> mi_slu3_seq { get; set; }

    public Nullable<int> mi_slu4_seq { get; set; }

    public Nullable<int> mi_slu5_seq { get; set; }

    public Nullable<int> mi_slu6_seq { get; set; }

    public Nullable<int> mi_slu7_seq { get; set; }

    public Nullable<int> mi_slu8_seq { get; set; }

    public Nullable<System.DateTime> DateCreated { get; set; }

    public Nullable<int> master_item_Id { get; set; }

    public Nullable<int> RecipeId { get; set; }

    public string ob_tax_1_active { get; set; }

    public string ob_tax_2_active { get; set; }

    public string ob_tax_3_active { get; set; }

    public string ob_tax_4_active { get; set; }

    public string ob_tax_5_active { get; set; }

    public string ob_tax_6_active { get; set; }

    public string ob_tax_7_active { get; set; }

    public string ob_tax_8_active { get; set; }

}

}
