
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InventoryPizzaExpress
{

using System;
    using System.Collections.Generic;
    
public partial class Store_Details
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Store_Details()
    {

        this.I_OrderDetails = new HashSet<I_OrderDetails>();

        this.I_StockTaking = new HashSet<I_StockTaking>();

        this.I_WasteDetails = new HashSet<I_WasteDetails>();

    }


    public int storeId { get; set; }

    public string storename { get; set; }

    public Nullable<int> MasterStoreId { get; set; }

    public string address { get; set; }

    public string city { get; set; }

    public string state { get; set; }

    public string email { get; set; }

    public string phone { get; set; }

    public string manager { get; set; }

    public Nullable<bool> isEM { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<I_OrderDetails> I_OrderDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<I_StockTaking> I_StockTaking { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<I_WasteDetails> I_WasteDetails { get; set; }

}

}
